#!/usr/bin/env bash
# IMP-004 (plan 2026-08-28): install the local commit-time gate hook.
#
# This repo has NO remote (`git remote -v` is empty), so push-based CI does not
# apply. Quality gates are enforced at `git commit` time instead: the generated
# hook runs scripts/precommit_ruff.sh (ruff + mypy + optional coverage) and then
# scripts/gate_tests.sh (pytest), blocking the commit on the first failure.
#
# Usage:   bash scripts/install_hooks.sh [REPO_ROOT]
# Default REPO_ROOT is `git rev-parse --show-toplevel`.
# Idempotent: a second run rewrites the hook byte-identically.
# Emergency bypass for a single commit: git commit --no-verify.
set -euo pipefail

root="${1:-$(git rev-parse --show-toplevel)}"

if [ ! -d "$root/.git" ]; then
  echo "install_hooks: not a git repo: $root" >&2
  exit 1
fi

mkdir -p "$root/.git/hooks"
hook="$root/.git/hooks/pre-commit"

cat > "$hook" <<'HOOK'
#!/bin/sh
# unsloth-quant-tui gate hook - GENERATED by scripts/install_hooks.sh (IMP-004).
# Edit the installer and re-run it; manual edits here are overwritten.
# Emergency bypass: git commit --no-verify.
root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$root" || exit 1

bash scripts/precommit_ruff.sh
rc=$?
if [ "$rc" -ne 0 ]; then
  echo "pre-commit: FAIL - ruff/mypy gate failed (scripts/precommit_ruff.sh)" >&2
  exit "$rc"
fi

bash scripts/gate_tests.sh
rc=$?
if [ "$rc" -ne 0 ]; then
  echo "pre-commit: FAIL - pytest gate failed (scripts/gate_tests.sh)" >&2
  exit "$rc"
fi

echo "pre-commit: gate OK"
HOOK

chmod +x "$hook"
echo "install_hooks: installed $hook"
